### ISSUE TITLE
[feature request] Support the -j (-json) option to output as formatted JSON.

### ISSUE THREAD

**Issue by aQutie** [laktak/gulp-hjson#1]
Hello, thank you for taking the time to wrap hjson for use with gulp.

Right now the default behavior when using the { to: 'json' } option is that the output json file is one continuous string without any formatting. Hjson now has an option using -j to output the json to a formatted file. It would be great if gulp-hjson supported another option, perhaps {output: 'formatted'} so that we could easily get a json file that is readable without having to open it in an editor and reformatting.

Thanks for the consideration. Cheers!

**Comment by laktak** [comment]
I'd use the JSON for distribution but if you want you can now use the `{ to: 'json', jsonSpace: ' ' }` options.

**Comment by aQutie** [comment]
@laktak Works perfect! I like the added touch of being able to control the number of spaces used to indent.

Many thanks for the effort and quick response.
